name: actions-slack-deployment
description: Action to post workflow status to Slack
author: fleetactions
inputs:
  workflow-status:
    description: 'The status of the job'
    required: true
  environment-name:
    description: 'Environment name for the deployment (staging, uat, production)'
    required: true
  deployment-type:
    description: 'Deployment type (i.e. Application, Infrastructure)'
    required: false
  slack-webhook-url:
    description: 'Slack webhook url for publishing the message'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
